version: '3.7'
services:
  nginx:
    image: nginx:1.18
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/app
    ports:
      - "8081:80"
  php-fpm:
    image: php:7.4-fpm
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app